# .streamlit/secrets.toml

# Supabase connection
[connections.supabase]
url = "https://krzqemzrypfdpgowjndh.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyenFlbXpyeXBmZHBnb3dqbmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjAyMTEsImV4cCI6MjA2NzUzNjIxMX0.AIK2kmdl2ZcpF_mhu_7incI_RIEClmtqh0duUt8U4JY"

# OpenRouter API keys for LLM providers
[openrouter]
API_KEY_QWEN    = "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"
API_KEY_MISTRAL = "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"
