# .streamlit/secrets.toml

# Supabase connection
[connections.supabase]
url = "https://krzqemzrypfdpgowjndh.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyenFlbXpyeXBmZHBnb3dqbmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjAyMTEsImV4cCI6MjA2NzUzNjIxMX0.AIK2kmdl2ZcpF_mhu_7incI_RIEClmtqh0duUt8U4JY"

# OpenRouter API keys for LLM providers
[openrouter]
API_KEY_QWEN    = "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"
API_KEY_MISTRAL = "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"
